builders:
  relationshipPartnersBuilder:
    import: 'package:consadole_partners_map/relationship_partners_builder.dart'
    builder_factories: ["relationshipPartnersBuilderFactory"]
    build_extensions: {".dart": [".g.dart"]}
    auto_apply: root_package
    build_to: source
targets:
  $default:
    builders:
      consadole_partners_map:relationshipPartnersBuilder:
        generate_for:
          include:
            - lib/relationship_partners_builder.dart
